png(file ="plot2.png") 
pow_consumption<-read.csv("household_power_consumption.txt", header = FALSE,sep=";", na.strings = "?",colClasses=c("character", "character", "numeric","numeric","numeric","numeric","numeric","numeric","numeric"),nrows=2880, skip=66636, col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
pow_consumption$dt<-strptime(paste(pow_consumption$Date,pow_consumption$Time), format="%d/%m/%Y%H:%M:%S")
plot(pow_consumption$dt, pow_consumption$Global_active_power, type="l", ylab="Global Active Power (kilowatts)" ,col="black", main="", xlab="")
dev.off()